name: Build ddns-go for OpenWrt x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync \
          unzip zlib1g-dev file wget

    - name: Download OpenWrt SDK (x86_64, 23.05.0)
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt-sdk
        cd openwrt-sdk
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Clone ddns-go package
      run: |
        cd openwrt-sdk/package
        git clone https://github.com/jeessy2/ddns-go-openwrt.git ddns-go

    - name: Configure build
      run: |
        cd openwrt-sdk
        make defconfig
        echo 'CONFIG_PACKAGE_ddns-go=y' >> .config
        echo 'CONFIG_PACKAGE_luci-app-ddns-go=y' >> .config
        make defconfig

    - name: Build packages
      run: |
        cd openwrt-sdk
        make package/ddns-go/compile -j$(nproc) V=s
        make package/luci-app-ddns-go/compile -j$(nproc) V=s

    - name: Upload .ipk
      uses: actions/upload-artifact@v2
      with:
        name: ddns-go-ipk
        path: |
          openwrt-sdk/bin/packages/x86_64/ddns-go/*.ipk
          openwrt-sdk/bin/packages/x86_64/luci/*.ipk
